#!/usr/bin/env bash
# Create root .env for SMS Monitor from existing secrets (never commit .env).
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"
ENV_FILE="$ROOT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  if grep -qE '^TELEGRAM_BOT_TOKEN=[^[:space:]]+' "$ENV_FILE" 2>/dev/null; then
    echo "✅ .env already has TELEGRAM_BOT_TOKEN"
    exit 0
  fi
fi

TOKEN="${TELEGRAM_BOT_TOKEN:-${SMS_MONITOR_BOT_TOKEN:-}}"
OWNER="${TELEGRAM_ALLOWED_USERS:-}"
SECRET="${API_SECRET_KEY:-}"

if [ -f "$ROOT_DIR/.env.aadhaar" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT_DIR/.env.aadhaar"
  set +a
  TOKEN="${TOKEN:-${AADHAAR_BOT_TOKEN:-}}"
  OWNER="${OWNER:-${AADHAAR_OWNER_IDS:-}}"
fi

if [ -f "$ROOT_DIR/.env.panel_search" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT_DIR/.env.panel_search"
  set +a
  OWNER="${OWNER:-${PANEL_SEARCH_OWNER_IDS:-}}"
  SECRET="${SECRET:-${PANEL_SEARCH_AUTH_KEY:-}}"
fi

TOKEN="${TOKEN:-${AADHAAR_BOT_TOKEN:-}}"
OWNER="${OWNER:-8674644868}"
if [ -z "$SECRET" ]; then
  SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
fi

if [ -z "$TOKEN" ]; then
  echo "❌ No Telegram token — set TELEGRAM_BOT_TOKEN or .env.aadhaar AADHAAR_BOT_TOKEN"
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by ensure_sms_env.sh — edit if needed
TELEGRAM_BOT_TOKEN=${TOKEN}
TELEGRAM_ALLOWED_USERS=${OWNER}
API_SECRET_KEY=${SECRET}
DATABASE_URL=sqlite:///./sms_monitor.db
PORT=8000
VIRTUS_MODULE_DB=https://virtus-module-default-rtdb.firebaseio.com
EOF
chmod 600 "$ENV_FILE"
echo "✅ Wrote $ENV_FILE (SMS Monitor / Virtus webhook)"
